services:
  web:
    image: wordrepresentation:1.0
    network_mode: "host"
    volumes:
      - /mnt/data/wordrep/model/:/workspace/model/
    command: python3 torch_server.py -c config/bert_en_config.json -p 58088