FROM machinelearning:1.2
USER root

RUN apt-get update
RUN apt-get install openjdk-8-jdk -y
RUN apt-get install maven -y
RUN rm -rf /workspace/*
COPY . /workspace
COPY settings.xml /usr/share/maven/conf/
RUN mkdir -p /root/.javacpp/cache/cuda-10.2-7.6-1.5.2-linux-x86_64.jar/org/bytedeco/cuda/linux-x86_64/
COPY libjnicudart.so /root/.javacpp/cache/cuda-10.2-7.6-1.5.2-linux-x86_64.jar/org/bytedeco/cuda/linux-x86_64/libjnicudart.so

#RUN mvn package -f pom.xml
RUN mvn package -f gpom.xml
# Run when the container launches
WORKDIR /workspace
CMD ["python3"]
