FROM machinelearning:1.2
USER root

RUN apt-get update
RUN apt-get install openjdk-8-jdk -y
RUN apt-get install maven -y
RUN rm -rf /workspace/*
COPY . /workspace
COPY settings.xml /usr/share/maven/conf/

#RUN mvn package -f pom.xml
RUN mvn package -f gpom.xml
# Run when the container launches
# ENV LD_LIBRARY_PATH /usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH
WORKDIR /workspace
CMD ["python3"]
